### Signup Route 
POST https://ticketing.dev/api/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "t@t.com",
  "password": "123456"
}


### Signin Route 
POST https://ticketing.dev/api/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "t@t.com",
  "password": "123456"
}


### Current User Route
GET https://ticketing.dev/api/users/currentuser HTTP/1.1

### Signout Route
POST https://ticketing.dev/api/users/signout HTTP/1.1

### 404 NOT FOUND
GET https://ticketing.dev/api/users/notfound404 HTTP/1.1